# Generated by Django 3.2.3 on 2021-05-31 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projcts', '0007_alter_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='users_like',
            field=models.ManyToManyField(blank=True, null=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
