# Generated by Django 3.2.3 on 2021-05-31 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projcts', '0008_project_users_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='images_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
