# Generated by Django 3.2.3 on 2021-05-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projcts', '0009_alter_project_users_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='users_like',
        ),
    ]
